service: ping-ng-apis

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  NG_LAMBDA_1:
    name: national-grid-test-api
    handler: pingng.pingng.lambda_handler
    description: sample_lambda
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"