name: Deploy from External Repository

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow

jobs:
  trigger_deploy_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in external repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/bhanuduggal/aws_python_tool_template/dispatches" \
            -d '{"event_type": "run-deploy", "client_payload": {"ACCESS_KEY": "${{ secrets.ACCESS_KEY }}", "SECRET_ACCESS_KEY": "${{ secrets.SECRET_ACCESS_KEY }}"}}'