name: Deploy from External Repository

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow

jobs:
  call_deploy_workflow:
    uses: bhanuduggal/aws_python_tool_template/.github/workflows/deploy.yml@main
